# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

    node-version: 12
- run: npm ci
- run: npm run build --if-present
- run: npm test
- name: run component tests
  run: npm run test:component
- name: run contract tests
  run: npm run test:contract
  env: 
    API: http://localhost:8080
- name: publish contracts
  env: 
    PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
    PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  run: npm run contract:publish 